
-- Anonymous visitor presence for the Admin dashboard.
-- visitor_code is a first-party browser code generated by the site.
create table if not exists public.visitors (
  visitor_code text primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  current_page text,
  device_type text,
  user_agent text,
  ip_address inet,
  audio_playing boolean not null default false,
  location_permission boolean not null default false,
  latitude double precision,
  longitude double precision
);
create index if not exists visitors_last_seen on public.visitors(last_seen desc);

-- Optional chat table for the live community chat.
create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  visitor_code text,
  display_name text not null check (char_length(display_name) between 1 and 30),
  message text not null check (char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);
create index if not exists chat_messages_time on public.chat_messages(created_at desc);
